### ISSUE TITLE
DPL: Constructors and operator= for DPC++ execution policies are not explicitly specified

### ISSUE THREAD

**Issue by andreyfe1** [uxlfoundation/oneAPI-spec#271]
The following are not explicitly specified for DPC++ execution policies:

- copy constructor
- move constructor
- copy assignment
- move assignment

Is their behavior considered to be default?
For example. What if an implementation decide to mark operator= as deleted, will it be considered as a deviation from the Spec?

**Comment by rarutyun** [comment]
From my perspective if we don't explicitly list the default members the behavior is as they are there with `= default` marker. The argument for that is the destructor. I believe that we didn't specify the destructor almost anywhere. But it's valid operation since we can create the objects on the stack (e.g. `device_policy`) and this is the desired scenario.

Even if we don't specify the layout explicitly I think we should consider prohibiting those default members as the breaking change. Consider one more example: Imagine that the class has all default members specified as `= default` without specifying the layout. I think user would assume that they can be called. Then, on the next version of the product the implementation has been changed and contains the reference in the layout which breaks the ability to call copy-assignment. To me it also looks like breaking change.

**Comment by akukanov** [comment]
I am sure marking copy/move operations as `= default` is not a good idea, because it might unnecessarily limit the implementation options, and it really does not mean much because the internals of a device policy are not exposed.

I think the best course of actions is to add the operations to the class and describe the expected semantics.

Tagging @rarutyun @danhoeflinger

**Comment by rarutyun** [comment]
> I think the best course of actions is to add the operations to the class and describe the expected semantics.

I don't feel strongly either way (status quo vs adding the operators with expected semantics). Perhaps, what you are suggesting is better to avoid ambiguity in the behavior. The thing is I saw several examples in C++ standard where "default" members are not specified for the class in the synopsis, so everybody just assumes they have a `= default` behavior (though, it might be hard to know exactly what's going on because, as you pointed out, there is no much information about class internals). I don't exactly remember, whether (for such cases I am talking about) there are some semantical requirements for "default" members.

Again, to avoid ambiguity what you are suggesting sounds reasonable.

Going back to my example with a destructor, I didn't find any mentioning of `= default` for destructor in C++ standard. It's explicitly defined in the synopsis when it has something "special": if it's non-trivial, `virtual`, `protected`, etc.

**Comment by danhoeflinger** [comment]
I suppose the way to think about this might be:
1) Does the specification explicitly require any of these to be defined in a particular way to make sense?
2) Do we see it as important to avoid any of these operations for performance reasons or otherwise?
3) What do we gain from specifying these as opposed to leaving them unspecified?

My answers:
1) I don't think so.  With our extensions, we match the C++ standard in specifying the policies to be accepted by universal/forwarding reference, which should not need these operations as far as I understand.  What happens to the policies inside the implementation is up to the implementer.
2) I'm not sure, I think this is probably something we can leave up to the implementer considering we don't specify the details of the device policy itself.
3) Right now, it is unclear what should happen for users if they copy / move / assign policies in their own code, specifying them would clear that up for users. 


With this in mind, I think specifying them by their semantics in similar language to the constructor from a differently named policy makes sense.  Its also probably a reasonable option to do nothing and leave them unspecified.

**Comment by akukanov** [comment]
Yes, the main motivation is to clarify for users what they can and cannot do with execution policies.

We have the options of:
1) disallowing copy/move operations for the device policies. For our implementation, that would be a breaking change though; I am not sure if we could argue that this was previously unspecified and so should not have been used.
2) saying that the copy/move operations are either (a) unspecified or (b) implementation-defined. That would leave implementors freedom to do what they want; the differences between (a) and (b), as I understand, is that (b) requires the implementation to define and document the behavior while (a) does not. For users, both would mean that these operations are not portable / not guaranteed to exist.
3) allowing copy/move and describing the expected semantics.
And in fact, the choice might be different for copy and move operations.

Going with (1) only makes sense if we think that copying/moving a device policy is plain wrong in [almost] all cases. A device policy carries two pieces of information - which queue to submit algorithm kernels to, and optionally which kernel name to use. The queue is obviously shared, but the kernel name, if specified, is supposedly unique and should be used for only one algorithm invocation in the code. That might be a reason to disallow at least copying; on the other hand, we cannot prevent using a single policy instance for multiple invocations, so no copying does not give much. I am not in favor of (1) therefore.

(2) would mean the specification discourages copy/move but does not prevent implementations to allow those. It's an easy way to keep status quo with a little more clarity. We'd likely need to complement it with some oneDPL project documentation. Also, our implementation is the only one so far, and the likely starting point for others; so its behavior might as well set the de-facto expectations.

(3) of course gives most clarity and guarantees portability.
